/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppNavbar: typeof import('./components/AppNavbar.vue')['default']
    AppSidebar: typeof import('./components/AppSidebar.vue')['default']
    ArticleDetail: typeof import('./components/ArticleDetail.vue')['default']
    CommentBanner: typeof import('./components/CommentBanner.vue')['default']
    CommentBar: typeof import('./components/CommentBar.vue')['default']
    PersonalResume: typeof import('./components/PersonalResume.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
